language: go
go:
- 1.7
- tip
env:
  matrix:
    - ES_VERSION=2.2.0
  allow_failures:
    - go: tip
before_script:
  - mkdir ${HOME}/elasticsearch
  - wget http://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzvf elasticsearch-${ES_VERSION}.tar.gz -C ${HOME}/elasticsearch
  - ls -alFR ${HOME}/elasticsearch
  - ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/bin/elasticsearch >& /dev/null &
  - sleep 15
